version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: banking_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bankadmin -d bankingzta"]
      interval: 10s
      timeout: 5s
      retries: 5

  opa:
    image: openpolicyagent/opa:latest
    container_name: banking_opa
    ports:
      - "8181:8181"
    volumes:
      - ./opa:/policies
    command:
      - "run"
      - "--server"
      - "--addr=0.0.0.0:8181"
      - "/policies/policy.rego"
      - "/policies/data.json"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: banking_keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command: 
      - "start-dev"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: