events {
    worker_connections 1024;
}

http {
    server {
        listen 443 ssl;
        server_name localhost;

        # 1. Your Server Certificates
        ssl_certificate     /home/nitro/Documents/banking-zta/certs/server.crt;
        ssl_certificate_key /home/nitro/Documents/banking-zta/certs/server.key;

        # 2. Demand the Client Certificate
        ssl_client_certificate /home/nitro/Documents/banking-zta/certs/ca.crt;
        ssl_verify_client on;

        # 3. SECURE API ROUTES (Forward to FastAPI Monolith)
        location ~ ^/(transfer|security|admin|accounts) {
            # Enforce Zero Trust Device Identity
            if ($ssl_client_verify != SUCCESS) {
                return 403 "Zero Trust Violation: Valid Client Certificate Required\n";
            }

            proxy_pass http://localhost:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-SSL-CERT $ssl_client_escaped_cert;
            proxy_set_header Authorization $http_authorization; 
        }

        # 4. FRONTEND ROUTE (Forward to React Vite Server)
        location / {
            proxy_pass http://localhost:5173;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # These two lines allow Vite's Hot-Reloading to work through Nginx
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}